### PR TITLE
Test PR - Added git util tests

### PR DESCRIPTION
**Pull request by mkenne11**
PR to test Git util tests.

Not ready to merge yet - requires cleanup

### CODE REVIEW

**Comment by mkenne11** [comment]
I wrote some tests for util git functions however these aren't working in the Travis CI build - they work on my local machine running electron-mocha (without Travis).

The tests fail on the following git command:
``` git "symbolic-ref" "--short" "-q" "HEAD"```

**Comment by mkenne11** [comment]
I attempted to replicate the Travis build by running git commands:
```
git clone --depth=50 https://github.com/railsware/upterm.git railsware/upterm
git fetch origin +refs/pull/1100/merge:
git checkout -qf FETCH_HEAD
```

**Comment by vlad-shatskyi** [comment]
@mkenne11 I'd like to switch to some git library in the future, so I'm not sure those tests are necessary.

**Comment by mkenne11** [comment]
No worries at all @vlad-shatskyi - I'll close the PR.

**Pull request closed without merging**
