### PR TITLE
Updated README to include an Arch Linux install guide (yaourt).

### PR DESCRIPTION
**Pull request by christianwico**
Added a new install entry to README for Arch Linux users since Black Screen is available for automated install via `yaourt` (AUR).

### CODE REVIEW

**Comment by vshatskyi** [comment]
Is there a way to automate AUR builds? Or maybe we could provide two packages: black-screen-bin and black-screen, where the latter would clone master and package the app on a user's machine?

**Comment by vshatskyi** [comment]
@christianwico the project was renamed to upterm. Would you be able to update the AUR package name?

**Comment by christianwico** [comment]
Unfortunately, I wasn't the host of the AUR build so I can't make any sort of changes to it. [Here's](https://aur.archlinux.org/packages/black-screen/) the link to the AUR page. Seems it was submitted by a `tensor5`...

**Comment by christianwico** [comment]
I've flagged the AUR as `Outdated`. The maintainer should be notified.

**Comment by vshatskyi** [comment]
@christianwico the maintainer changed the name. Could you please update the PR? https://aur.archlinux.org/packages/upterm/

**Comment by christianwico** [comment]
Made the new commit to this branch.

**Comment by vshatskyi** [comment]
Thanks, @christianwico!

**Pull request merged**
