### PR TITLE
Fix for Multi-line pasting is broken #1309

### PR DESCRIPTION
**Pull request by ABouzo**
This should fix the issue for multi-line pasting, at least for multiple command. For something like functions would need to be added to the parser.

### CODE REVIEW

**Comment by le0pard** [comment]
Thanks @ABouzo. Does PR ready for review? :)

**Comment by ABouzo** [comment]
Yes, it is. I'm not sure what the process is to mark this as ready for review.

**Comment by le0pard** [comment]
Don't worry. I just was not sure, that came more commits. I will try to review it tomorrow.

**Comment by ABouzo** [comment]
Thank you!

**Comment by le0pard** [comment]
@ABouzo big thanks!

**Pull request merged**
