### PR TITLE
Changes to ps autocomplete for monaco

### PR DESCRIPTION
**Pull request by mkenne11**
Changes made to the ps autocomplete provider to work with monaco based Suggestion items.

### CODE REVIEW

**Comment by mkenne11** [comment]
To show how ps auto-complete now works with this PR I have attached a animated screenshot capture. The capture shows a sample command with multiple option values selected.

**Comment by vlad-shatskyi** [comment]
This is awesome, @mkenne11, thanks!

**Comment by mkenne11** [comment]
No worries thanks @vlad-shatskyi

**Comment by vlad-shatskyi** [comment]
@mkenne11 it fails on my computer (macOS 10.12) with
```
ps: egid: keyword not found
ps: egroup: keyword not found
```

Although, works with these changes:

image

Should I apply them?

**Comment by mkenne11** [comment]
Sorry @vlad-shatskyi I just saw your msg. Yes please apply. Tbh I'm not familiar with the difference between  mac os (and other BSD-based ditributions) vs Linux.
Looking at the ```ps``` man pages for Linux and BSD, BSD ```ps -eo comm``` appears to be equiv to ```ps -eo cmd``` in Linux.

**Comment by mkenne11** [comment]
It could be awkward though - having to check the type if Linux or BSD is running each time before you call this method. Is the OS type easy to check?

**Comment by vlad-shatskyi** [comment]
@mkenne11, it doesn't require IO to check platform. Although, there is more to fix than I originally thought, so I'll leave it as is for now.

**Pull request merged**
